[build]
  command = "npx prisma generate && npx next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  included_files = ["node_modules/.prisma/client/*.node", "node_modules/@prisma/engines/*.node"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
