import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { writeAudit } from "@/lib/audit";

export async function PATCH(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const reportId = Number(id);
  const body = await req.json();
  const { action, operatorId } = body;

  const report = await prisma.report.findUnique({ where: { id: reportId } });
  if (!report) return Response.json({ error: "报量不存在" }, { status: 404 });

  // support both old "status" field and new "action" field
  const newStatus = action === "verify"
    ? "verified"
    : action === "reject"
    ? "rejected"
    : body.status ?? report.status;

  if (!["pending", "verified", "rejected"].includes(newStatus)) {
    return Response.json({ error: "Invalid status" }, { status: 400 });
  }

  const updated = await prisma.report.update({
    where: { id: reportId },
    data: {
      status: newStatus,
      verifiedBy: operatorId ?? "admin",
      verifiedAt: new Date(),
    },
  });

  await writeAudit({
    tableName: "Report",
    recordId: reportId,
    field: "status",
    oldValue: report.status,
    newValue: newStatus,
    operatorId: operatorId ?? "admin",
    action: "update",
  });

  // ── 签证自动捕捉（Task #5）──────────────────────────────────────────────
  // 每当一条报量被核准，检查该工人在该项目下未被签证覆盖的核准报量数量
  // 累积达到 AUTO_VISA_THRESHOLD 条时，自动生成一条待审签证
  if (newStatus === "verified") {
    const AUTO_VISA_THRESHOLD = 5;
    const uncovered = await prisma.report.findMany({
      where: {
        workerId: report.workerId,
        project: report.project,
        status: "verified",
        flagVisa: false,
      },
      select: { id: true },
    });

    if (uncovered.length >= AUTO_VISA_THRESHOLD) {
      const sourceIds = uncovered.map((r) => r.id);
      const visa = await prisma.visa.create({
        data: {
          title: `自动签证 · ${report.workerName} · ${uncovered.length}条报量`,
          amount: 0,
          submitter: report.workerName,
          project: report.project,
          status: "pending",
          autoGenerated: true,
          sourceReportIds: sourceIds,
        },
      });

      // 标记这些报量已被签证覆盖
      await prisma.report.updateMany({
        where: { id: { in: uncovered.map((r) => r.id) } },
        data: { flagVisa: true },
      });

      await writeAudit({
        tableName: "Visa",
        recordId: visa.id,
        field: "status",
        oldValue: null,
        newValue: "pending",
        operatorId: "system",
        action: "create",
      });
    }
  }
  // ────────────────────────────────────────────────────────────────────────

  return Response.json(updated);
}
